language: php
php:
  - 7.0
  - 7.1
  - 7.2
env:
  - DB=mysql

install:
  - composer
  - pecl
before_script:
  - sh -c "mysql -e 'create database IF NOT EXISTS test;'";
  - sh -c "echo 'database=test' >> App/config/database.ini"
  - composer install
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: vendor/bin/phpunit  --configuration test/phpunit.xml
